server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    com.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

api:
  common:
    version: 1.0.0
    title: Product API
    description: Product API
    termsOfServiceUrl: TERMS OF SERVICE URL
    license: License
    licenseUrl: LICENSE URL

    contact:
      name: frfontoura
      url: https://github.com/frfontoura
      email: test@test.com
